### ISSUE TITLE
base.url undefined and 500 errors.

### ISSUE THREAD

**Issue by Myu-Unix** [IHTSDO/ihtsdo-refset-management-service#2]
Hello dears,

I am in the process of building and deploying the Refset Management Service on a VM.

I followed the steps from https://confluence.ihtsdotools.org/display/REFSET/PROD+Deploy+Instructions and https://confluence.ihtsdotools.org/display/REFSET/Building+and+Deploying+in+Eclipse and I can access the UI but I have multiples issues.

**1. base.url is undefined**

![base url_undefined](https://user-images.githubusercontent.com/1077135/84355047-3df9af00-abc2-11ea-86be-8849f6518a13.png)

While it seems properly set in config.properties

![base url_set](https://user-images.githubusercontent.com/1077135/84355057-405c0900-abc2-11ea-8740-e67ec49fd965.png)

I am building with `mvn -Dconfig.artifactId=refset-config-prod clean install`

**2. Multiples 500 errors**

May be related to the first issue but I have multiples HTTP 500 errors popping up.

![error_500](https://user-images.githubusercontent.com/1077135/84362903-3d671580-abce-11ea-9906-7eb0d323f8e8.png)

**3. API Key from SCT Browser**

Furthermore, I would like to plug it on a terminology server but I didn't find how I am supposed to get the information about the API Key from my existing SCT Browser :

`terminology.handler.BROWSER.apiKey=`

Could you help me and give me some hints/guidance on those points ?

Cheers,

**Comment by RichardAWood** [comment]
Hello Myu,

For issues #1 and #2, my initial thought is these errors look similar to ones I experience when I forget to set refset.config on tomcat (for example, on my system: 
-Drefset.config="C:\refset\config\config.properties")

For issue #3, the apiKey is only used for pulling Google translation suggestions in the Translation portion of the tool.  This property can be left blank, and it will simply not pull translations from the GoogleTranslate API.  Alternately, you can create your own apiKey and use it (https://cloud.google.com/translate). 

Hope these help, 
-Rick

**Comment by Myu-Unix** [comment]
Hello Rick,

Thanks for the answer(s) to me it seems well set : 

In /etc/default/tomcat9 : 

`JAVA_OPTS="-Djava.awt.headless=true -Xmx3000m -XX:+UseConcMarkSweepGC -Drefset.config=/var/lib/tomcat9/conf/config.properties"`

I'll retry the setup from the beginning. Is there any "from scratch" how-to to set this up ? The 2 links I have tried are for your own Prod and UAT deployment on Windows and to be fair seems a bit lacking in details for a layman/external person.

Many thanks for your support !

Cheers,

**Comment by RichardAWood** [comment]
The best "from scratch" how-to we have is the "Building and Deploying in Eclipse" page you referenced above.  The other page "PROD Deploy Instructions" is specifically meant for managing the SNOMED deployment.

Beyond that, your tomcat setup looks good.  If you're comfortable doing so, would you be willing to send me your config.properties (after removing any sensitive information).  There are some changes to the terminology handlers currently in progress, and I'm wondering if some of the errors you're seeing could be caused by those.

Personal email: rwood@westcoastinformatics.com

Best,
-Rick

**Comment by Myu-Unix** [comment]
Sure, done, thank you ! :+1:
